version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies..
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands...
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...

artifacts:
  files:
    - '**/*'
    base-directory: build
cache:
  paths:
    - 'node_modules/**/*'
